# Generated by Django 4.1.1 on 2022-09-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=100, verbose_name='oximetria')),
                ('frecuencia_respiratoria', models.CharField(max_length=100, verbose_name='frecuencia_respiratoria')),
                ('frecuencia_cardiaca', models.CharField(max_length=100, verbose_name='frecuencia_cardiaca')),
                ('temperatura', models.CharField(max_length=100, verbose_name='temperatura')),
                ('precion_arterial', models.CharField(max_length=100, verbose_name='precion_arterial')),
                ('glicemias', models.CharField(max_length=100, verbose_name='glicemias')),
            ],
        ),
    ]
