# Generated by Django 4.1.1 on 2022-09-16 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('Contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('rol_usuario', models.CharField(max_length=100, verbose_name='frecuencia_cardiaca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('resumen_historia_clinica', models.CharField(max_length=100, verbose_name='resumen_historia_clinica')),
                ('mecicamentos_terapidas', models.CharField(max_length=100, verbose_name='mecicamentos_terapidas')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='diagnostico')),
                ('sugerencia_cuidado', models.CharField(max_length=100, verbose_name='sugerencia_cuidado')),
                ('signos_vitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='productApp.signosvitales')),
            ],
        ),
    ]
