# Generated by Django 4.1.1 on 2022-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_usuario_historiaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(max_length=100, verbose_name='rol_usuario'),
        ),
    ]
