# Generated by Django 4.1.1 on 2022-09-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0008_alter_usuario_rol_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to='productApp.usuario')),
            ],
        ),
    ]
