# Generated by Django 4.1.1 on 2022-09-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0009_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Cedula', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Celular', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('historia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='productApp.historiaclinica')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_paciente_id', to='productApp.usuario')),
            ],
        ),
    ]
