# Generated by Django 4.1.1 on 2022-09-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Cedula',
            field=models.CharField(max_length=100, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Celular',
            field=models.CharField(max_length=100, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Cedula', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Celular', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('historia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_paciente_id', to='productApp.historiaclinica')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar_paciente_id', to='productApp.paciente')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar_usuario_id', to='productApp.usuario')),
            ],
        ),
    ]
