# Generated by Django 4.1.1 on 2022-09-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0011_alter_paciente_apellido_alter_paciente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id_enfermero', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('Celular', models.CharField(max_length=100, verbose_name='Celular')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero_paciente_id', to='productApp.paciente')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero_usuario_id', to='productApp.usuario')),
            ],
        ),
    ]
