# Generated by Django 4.1.1 on 2022-09-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0012_enfermero'),
    ]

    operations = [
        migrations.CreateModel(
            name='pacientesAsignados',
            fields=[
                ('cant_pacientes', models.AutoField(primary_key=True, serialize=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_paciente_asignado', to='productApp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_medico_asignado', to='productApp.paciente')),
            ],
        ),
    ]
