# Generated by Django 4.1.1 on 2022-09-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0013_pacientesasignados'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiasClinicas',
            fields=[
                ('cant_historiasClinicas', models.AutoField(primary_key=True, serialize=False)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hisoria_medico_asignado', to='productApp.historiaclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_hsitoria_asignado', to='productApp.medico')),
            ],
        ),
    ]
